apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector: 
    app: {{ .Values.spec.selector.matchLabels.app }}
  type: LoadBalancer
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  