
metadata: 
  name: demo
  namespace: demo
  labels:
    app: demo
  
spec:
  selector:
    matchLabels:
      app: demo  
  template:
    metadata:
      labels:
        app: demo     

deployment:
  spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
        protocol: TCP
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"

service:
  ports:
  - port: 80
    targetPort: 80


